My PR for Homework #8
Otus-DevOps-2019-08/kovtalex_infra pull request #8
Opened 2019-10-16 12:23 UTC by kovtalex

# Выполнено ДЗ №8

 - [X] Основное ДЗ
 - [X] Задание со *

## В процессе сделано:
 - Установлен Ansible
 - Рассмотрены различные варианты написания inventory (ini, yaml, static json, dynamic json)
 - Рассмотрена работа с группами хостов
 - Рассмотрена структура  плейбуков
 - Разработан скрипт для динамического inventory json

## Как запустить проект:
 - terraform apply -auto-approve
 - ansible-playbook clone.yml

## Как проверить работоспособность:
 - ansible all -m ping

## PR checklist
 - [X] Выставил label с номером домашнего задания
 - [X] Выставил label с темой домашнего задания

2019-10-16 12:26 UTC, kovtalex commented
Локально скрипт отрабатывает и отдает динамический json из стейта инфраструктуры stage, но тест тревиса не проходит((

2019-10-16 19:11 UTC, SablinIgor requested changes
Приветствую!

Такой скрипт создания динамического инвентори не сможет корректно отработать на агенте Тревиса, так как не сможет корректно выполнить команду терраформа. Ведь необходимых для этого учетных данных нет в репозитории?

Рекомендую поставить в настройку ансибла указание использовать статический инвентори. Описания алгоритма вычисления динамического инвентори в README вполне достаточно.

Пока возвращаю на доработку, надеюсь, что после правок, тесты Тревиса пройдут успешно.

2019-10-16 20:13 UTC, kovtalex commented
Добрый вечер! Исправил ansible.cfg. Тесты Travis пройдены. Динамический инвентори описан в README.md

2019-10-17 06:26 UTC, SablinIgor approved these changes
Отлично!

ДЗ принимаю.

2019-10-17 06:43 UTC, merged